### ISSUE TITLE
Is this repository actively maintained?

### ISSUE THREAD

**Issue by scottcunningham** [okta/oktasdk-python#12]
Hi all,

Just wondering if this repo is actively maintained or whether I should just be using the REST API directly with something like requests. I ask because I see there are a few unanswered issues and PRs over the past few months.

**Comment by scottcunningham** [comment]
I think that is a no. For anyone who's curious, I ended up re-implementing it myself.

**Comment by adaeran** [comment]
@lboyette-okta could you merge pr's?

**Comment by scottcunningham** [comment]
Okay, I guess the Okta devs closing this issue without responding is a definitive "no" to my question. Cheers.

**Comment by tbelote-okta** [comment]
Sorry @scottcunningham this repo is now actively maintained and we have a CLA for merging PRs. We have multiple python devs on the team, maintaining this repo is important to us.

**Comment by scottcunningham** [comment]
Thanks for the update @tbelote-okta! If the repo is likely to become active again, I'll try to take a look at my project from last February and figure out what the issues with this SDK were and the missing features that prompted me to write my own wrapper and try to contribute them back.
