### ISSUE TITLE
HTTP delete requests returns `204 No Content` But keyword fail

### ISSUE THREAD

**Issue by adaeran** [okta/oktasdk-python#15]
It fails because the method try to return Utils.deserialize when response.text is empty --> "No JSON object could be decoded"

So either 
1. Return None on all  204 expected keywords
Or
2. At Utils.deserialize add one more if case:
Util.py line:19
```
        if from_data:
            json_dump = {}
        elif isinstance(from_data, six.text_type) or isinstance(from_data, six.string_types):
            json_dump = json.loads(from_data)
        else:
            json_dump = from_data
```
Or whatever you think is fit here

**Comment by tbelote-okta** [comment]
Thanks! I have pushed an update.
