### ISSUE TITLE
Line 20 in utils.py throws exception

### ISSUE THREAD

**Issue by Michael-Hedges** [okta/oktasdk-python#18]
When calling UserClient.delete_user(uid),  oktasdk-python/okta/framework/Utils.py line 20 throws an exception (ValueError: No JSON object could be decoded). Presumably, whatever the okta API is returning is either not JSON, or is being improperly parsed.
What's that about?

**Comment by tbelote-okta** [comment]
Thanks for the feedback. You're right we weren't handling the 204 no response correctly. I have pushed an update.

**Comment by Michael-Hedges** [comment]
Thanks very much for the fix! =)
