### ISSUE TITLE
pip install broken?

### ISSUE THREAD

**Issue by flyinprogrammer** [okta/oktasdk-python#3]
```
root:~# pip install okta
Collecting okta
  Could not find a version that satisfies the requirement okta (from versions: )
No matching distribution found for okta

root:~# pip --version
pip 7.0.3 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

**Comment by slessans** [comment]
The issue with this is that PIP does not find the proper nested packages.... the `find_packages` function in setup.py should be changed to use the version `from setuptools import find_packages` or just made to be recursive.

**Comment by slessans** [comment]
i will create a pull request when I have time

**Comment by lboyette-okta** [comment]
This is now fixed
