### ISSUE TITLE
Assign roles to User

### ISSUE THREAD

**Issue by nicolastrres** [okta/oktasdk-python#42]
Hi everyone, I am looking for a way to [assign roles to a user](http://developer.okta.com/docs/api/resources/roles.html#assign-role-to-user). Specifically I am trying to make a user administrator of an application. Is there some way to do that using the oktasdk at this moment?

**Comment by jmelberg-okta** [comment]
@nicolastrres: We haven't added this into the SDK yet. However, you can assign the `APP_ADMIN` role by making a `POST` request to the `/roles` endpoint:
 
```python
import requests

url = 'https://{}/api/v1/users/{}/roles'.format(okta_org, user_id)

okta_headers = {
    'accept': "application/json",
    'content-type': "application/json",
    'authorization': "SSWS {{API_TOKEN}}",
}

payload = {
      'type': 'APP_ADMIN'
}

r = requests.post(url, data=payload, headers=okta_headers)
# print r.json
```
